# Generated by Django 6.0.3 on 2026-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
