# Generated by Django 6.0.3 on 2026-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
