# Generated by Django 6.0.3 on 2026-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_options_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_components',
            field=models.CharField(default=1, max_length=455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
