# Generated by Django 6.0.3 on 2026-04-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
