# Generated by Django 6.0.3 on 2026-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default=1, upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
