# Generated by Django 6.0.3 on 2026-04-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_free_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
