# Generated by Django 6.0.1 on 2026-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_area_pincode_user_city_user_house_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_no',
            field=models.PositiveIntegerField(),
        ),
    ]
