# Generated by Django 6.0.3 on 2026-05-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
